hearingCentreActivationDates:
  birmingham: ${IA_HEARING_CENTRE_ACTIVATION_DATE_BIRMINGHAM:2019-12-03}
  bradford: ${IA_HEARING_CENTRE_ACTIVATION_DATE_BRADFORD:2019-09-16}
  coventry: ${IA_HEARING_CENTRE_ACTIVATION_DATE_COVENTRY:2019-01-01}
  glasgow: ${IA_HEARING_CENTRE_ACTIVATION_DATE_GLASGOW:2020-01-14}
  glasgowTribunalsCentre: ${IA_HEARING_CENTRE_ACTIVATION_DATE_GLASGOW_TRIBUNALS_CENTRE:2019-01-01}
  hattonCross: ${IA_HEARING_CENTRE_ACTIVATION_DATE_HATTON_CROSS:2019-12-10}
  manchester: ${IA_HEARING_CENTRE_ACTIVATION_DATE_MANCHESTER:2019-01-01}
  newcastle: ${IA_HEARING_CENTRE_ACTIVATION_DATE_NEWCASTLE:2019-01-01}
  newport: ${IA_HEARING_CENTRE_ACTIVATION_DATE_NEWPORT:2019-09-23}
  northShields: ${IA_HEARING_CENTRE_ACTIVATION_DATE_NORTH_SHIELDS:2019-11-26}
  nottingham: ${IA_HEARING_CENTRE_ACTIVATION_DATE_NOTTINGHAM:2019-01-01}
  taylorHouse: ${IA_HEARING_CENTRE_ACTIVATION_DATE_TAYLOR_HOUSE:2019-01-01}
  belfast: ${IA_HEARING_CENTRE_ACTIVATION_DATE_GLASGOW:2020-01-14}
  harmondsworth: ${IA_HEARING_CENTRE_ACTIVATION_DATE_HARMONDSWORTH:2023-09-21}
  hendon: ${IA_HEARING_CENTRE_ACTIVATION_DATE_HENDON:2023-09-21}
  yarlsWood: ${IA_HEARING_CENTRE_ACTIVATION_DATE_YARLS_WOOD:2023-09-21}
  bradfordKeighley: ${IA_HEARING_CENTRE_ACTIVATION_DATE_BRADFORD_KEIGHLEY:2023-09-21}
  mccMinshull: ${IA_HEARING_CENTRE_ACTIVATION_DATE_MCC_MINSHULL:2023-09-21}
  mccCrownSquare: ${IA_HEARING_CENTRE_ACTIVATION_DATE_MCC_CROWN_SQUARE:2023-09-21}
  manchesterMags: ${IA_HEARING_CENTRE_ACTIVATION_DATE_MANCHESTER_MAGS:2023-09-21}
  nthTyneMags: ${IA_HEARING_CENTRE_ACTIVATION_DATE_NTH_TYNE_MAGS:2023-09-21}
  leedsMags: ${IA_HEARING_CENTRE_ACTIVATION_DATE_LEEDS_MAGS:2023-09-21}
  alloaSherrif: ${IA_HEARING_CENTRE_ACTIVATION_DATE_ALLOA_SHERRIF:2023-09-21}

hearingCentreCatchmentAreas:
  bradford:
    - "BD"
    - "DN"
    - "HD"
    - "HG"
    - "HU"
    - "HX"
    - "LS"
    - "S"
    - "WF"
    - "YO"
  manchester:
    - "BB"
    - "BL"
    - "CH"
    - "CW"
    - "FY"
    - "LL"
    - "ST"
    - "L"
    - "LA"
    - "M"
    - "OL"
    - "PR"
    - "SK"
    - "WA"
    - "WN"
  newport:
    - "BA"
    - "BS"
    - "CF"
    - "DT"
    - "EX"
    - "HR"
    - "LD"
    - "NP"
    - "PL"
    - "SA"
    - "SN"
    - "SP"
    - "TA"
    - "TQ"
    - "TR"
  taylorHouse:
    - "AL"
    - "BN"
    - "BR"
    - "CB"
    - "CM"
    - "CO"
    - "CR"
    - "CT"
    - "DA"
    - "E"
    - "EC"
    - "EN"
    - "IG"
    - "IP"
    - "ME"
    - "N"
    - "NR"
    - "NW"
    - "RH"
    - "RM"
    - "SE"
    - "SG"
    - "SS"
    - "TN"
    - "W"
    - "WC"
  newcastle:
    - "CA"
    - "DH"
    - "DL"
    - "NE"
    - "SR"
    - "TS"
  birmingham:
    - "B"
    - "CV"
    - "DE"
    - "DY"
    - "GL"
    - "HP"
    - "LE"
    - "LN"
    - "LU"
    - "MK"
    - "NG"
    - "NN"
    - "OX"
    - "PE"
    - "RG"
    - "SY"
    - "TF"
    - "WD"
    - "WR"
    - "WS"
    - "WV"
  hattonCross:
    - "BH"
    - "GU"
    - "HA"
    - "KT"
    - "PO"
    - "SL"
    - "SM"
    - "SO"
    - "SW"
    - "TW"
    - "UB"
  glasgow:
    - "AB"
    - "DD"
    - "DG"
    - "EH"
    - "FK"
    - "G"
    - "HS"
    - "IV"
    - "KA"
    - "KW"
    - "KY"
    - "ML"
    - "PA"
    - "PH"
    - "TD"
    - "ZE"
    - "BT"
