logging.level:
  root: info
  org.springframework.web: debug
  uk.gov.hmcts: debug

ref-data-case-worker-api.url: http://wiremock
prof.ref.data.url: http://wiremock
prof.ref.data.path.org.users: /refdata/external/v1/organisations/users
prof.ref.data.path.org.organisation: /refdata/external/v1/organisations

idam:
  system:
    scope: "openid profile authorities"

launchDarkly:
  sdkKey: ${IA_LAUNCH_DARKLY_SDK_KEY:sdk-key}
