hearingCentreMappings:
  birmingham:
    - "Ashwell"
    - "Aylesbury"
    - "Bedford"
    - "Birmingham"
    - "Blakenhurst"
    - "Brinsford"
    - "Brockhill"
    - "Bullingdon"
    - "Eastwood Park"
    - "Featherstone"
    - "Fosse Way"
    - "Foston Hall"
    - "Five Wells"
    - "Gartree"
    - "Glen Parva"
    - "Gloucester"
    - "Grendon/Spring Hill"
    - "Hewell Grange"
    - "Leicester"
    - "Leyhill"
    - "Lincoln"
    - "Littlehey"
    - "Long Lartin"
    - "Lowdham Grange"
    - "Morton Hall"
    - "North Sea Camp"
    - "Nottingham"
    - "Oakwood"
    - "Onley"
    - "Peterborough"
    - "Reading"
    - "Rye Hill"
    - "Shrewsbury"
    - "Spring Hill"
    - "Stafford"
    - "Stocken"
    - "Stoke Heath"
    - "Sudbury"
    - "Swinderby"
    - "Swinfen Hall"
    - "Wellingborough"
    - "Whatton"
    - "Whitemoor"
    - "Woodhill"
  bradford:
    - "Acklington"
    - "Askham Grange"
    - "Castington"
    - "Deerbolt"
    - "Derwentside"
    - "Doncaster"
    - "Durham"
    - "Everthorpe"
    - "Frankland"
    - "Full Sutton"
    - "Hatfield"
    - "Holme House"
    - "Hull"
    - "Humber"
    - "Kirklevington Grange"
    - "Leeds"
    - "Lindholme"
    - "Low Newton"
    - "Moorland Closed"
    - "Moorland Open"
    - "New Hall"
    - "Northallerton"
    - "Ranby"
    - "Wakefield"
    - "Wealstun"
    - "Wetherby"
    - "Wolds"
  glasgow:
    - "Addiewell"
    - "Barlinnie"
    - "Castle Huntly"
    - "Cornton Vale"
    - "Dumfries"
    - "Dungavel"
    - "Edinburgh, Saughton"
    - "Glenochil"
    - "Grampian"
    - "Greenock"
    - "Hydebank Wood"
    - "Inverness"
    - "Kilmarnock"
    - "Larne House"
    - "Low Moss"
    - "Magilligan"
    - "Maghaberry"
    - "Perth"
    - "Polmont"
    - "Shotts"
    - "Stirling"
  hattonCross:
    - "Albany"
    - "Brixton"
    - "Bronzefield"
    - "Camp Hill"
    - "Coldingley"
    - "Colnbrook"
    - "Downview"
    - "Feltham"
    - "Harmondsworth"
    - "High Down"
    - "Holloway"
    - "Huntercombe"
    - "Isle of Wight"
    - "Kingston"
    - "Latchmere House"
    - "Lewes"
    - "Parkhurst"
    - "Send"
    - "The Mount"
    - "Wandsworth"
    - "Winchester"
    - "Wormwood Scrubs"
  manchester:
    - "Altcourse"
    - "Berwyn"
    - "Buckley Hall"
    - "Dovegate"
    - "Drake Hall"
    - "Forest Bank"
    - "Garth"
    - "Haverigg"
    - "Hindley"
    - "Kennet"
    - "Kirkham"
    - "Lancaster"
    - "Lancaster Farms"
    - "Liverpool"
    - "Manchester"
    - "Preston"
    - "Risley"
    - "Styal"
    - "Thorn Cross"
    - "Werrington"
    - "Wymott"
  newcastle:
    - "Northumberland"
  newport:
    - "Ashfield"
    - "Bristol"
    - "Cardiff"
    - "Channings Wood"
    - "Dartmoor"
    - "Dorchester"
    - "Erlestoke"
    - "Exeter"
    - "Guys Marsh"
    - "Parc"
    - "Portland"
    - "Prescoed"
    - "Shepton Mallet"
    - "Swansea"
    - "The Verne"
    - "The Weare"
    - "Usk"
  taylorHouse:
    - "Belmarsh"
    - "Blantyre House"
    - "Blundeston"
    - "Brookhouse"
    - "Bullwood Hall"
    - "Bure"
    - "Canterbury"
    - "Chelmsford"
    - "Cookham Wood"
    - "East Sutton Park"
    - "Edmunds Hill"
    - "Elmley"
    - "Ford"
    - "Highpoint"
    - "Hollesley Bay/Hmyoi Warren Hill"
    - "Isis"
    - "Maidstone"
    - "Norwich"
    - "Pentonville"
    - "Rochester"
    - "Standford Hill"
    - "Swaleside"
    - "Thameside"
    - "Tinsley House"
    - "Warren Hill"
    - "Wayland"
  yarlswood:
    - "Yarlswood"






