java:
  image: 'https://hmctspublic.azurecr.io/ia/case-api:latest'
  ingressHost: ia-case-api-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
  applicationPort: 8090
  aadIdentityName: ia
  environment:
    POSTGRES_PORT: 5432
    POSTGRES_HOST: ia-case-api-postgres-db-v15-{{ .Values.global.environment }}.postgres.database.azure.com
    POSTGRES_USERNAME: pgadmin
    POSTGRES_CONNECTION_OPTIONS: "?sslmode=require"
    PROF_REF_DATA_URL: "http://rd-professional-api-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal"
    REF_DATA_CASE_WORKER_URL: "http://rd-caseworker-ref-api-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal"
    IA_CASE_DOCUMENTS_API_URL: "http://ia-case-documents-api-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal/"
    IA_CASE_NOTIFICATIONS_API_URL: "http://ia-case-notifications-api-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal/"
    IA_TIMED_EVENT_SERVICE_URL: "http://ia-timed-event-service-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal/"
    IA_TIMED_EVENT_SERVICE_ENABLED: "false"
    IA_CASE_PAYMENTS_API_URL: "http://ia-case-payments-api-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal/"
    IA_HOME_OFFICE_INTEGRATION_API_URL: "http://ia-home-office-integration-api-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal/"
    IA_HOME_OFFICE_INTEGRATION_ENABLED: "false"
    IA_IDAM_REDIRECT_URI: "https://ia-case-api-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal/oauth2/callback"
    CCD_URL: "http://ccd-data-store-api-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal"
    AAC_URL: "http://aac-manage-case-assignment-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal"
    CCD_GW_URL: "http://dm-store-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal"
    DM_URL: "http://dm-store-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal"
    IDAM_URL: "https://idam-api.{{ .Values.global.environment }}.platform.hmcts.net"
    OPEN_ID_IDAM_URL: "https://idam-web-public.{{ .Values.global.environment }}.platform.hmcts.net"
    S2S_URL: "http://rpe-service-auth-provider-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal"
    IS_SAVE_AND_CONTINUE_ENABLED: "false"
    ROLE_ASSIGNMENT_URL: "http://am-role-assignment-service-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal"
    COMMON_DATA_API: http://rd-commondata-api-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
    CASE_DOCUMENT_AM_URL: "http://ccd-case-document-am-api-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal"
    IA_HEARINGS_API_URL: "http://ia-hearings-api-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal/"
    LOCATION_REF_DATA_URL: "http://rd-location-ref-api-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal"
    LEGAL_REP_BUILD_CASE_DUE_IN_DAYS: 28
    LEGAL_REP_BUILD_CASE_ADA_DUE_IN_DAYS: 13
    LEGAL_REP_BUILD_CASE_DUE_IN_DAYS_FROM_SUBMISSION_DATE: 42
    LEGAL_REP_HEARING_REQUIREMENTS_DUE_IN_DAYS: 5
    LEGAL_REP_REVIEW_DUE_IN_DAYS: 5
    REQUEST_RESPONDENT_EVIDENCE_DUE_IN_DAYS: 14
    REQUEST_RESPONDENT_EVIDENCE_ADA_DUE_IN_DAYS: 3
    REQUEST_RESPONDENT_REVIEW_DUE_IN_DAYS: 14
    REQUEST_RESPONDENT_REVIEW_ADA_DUE_IN_DAYS: 2
    APPELLANT_REASONS_FOR_APPEAL_DUE_IN_DAYS: 28
    PAYMENT_AFTER_REMISSION_REJECTION_DUE_IN_MINUTES: 20160
    PAYMENT_EA_HU_NO_REMISSION_DUE_IN_MINUTES: 20160
    ADA_CASE_LISTED_DIRECTION_DUE_IN_DAYS: 15
  postgresql:
    auth:
      username: ia_case_api
      password: ${PG_AUTH_VALUES_YAML_PASS}
      database: ia_case_api
    service:
      port: 5432
  keyVaults:
    ia:
      resourceGroup: ia
      secrets:
        - name: docmosis-enabled
          alias: IA_DOCMOSIS_ENABLED
        - name: em-stitching-enabled
          alias: IA_EM_STITCHING_ENABLED
        - name: submit-hearing-requirements-enabled
          alias: IA_SUBMIT_HEARING_REQUIREMENTS_ENABLED
        - name: system-username
          alias: IA_SYSTEM_USERNAME
        - name: system-password
          alias: IA_SYSTEM_PASSWORD
        - name: idam-client-id
          alias: IA_IDAM_CLIENT_ID
        - name: idam-secret
          alias: IA_IDAM_SECRET
        - name: s2s-secret
          alias: idam.s2s-auth.totp_secret
        - name: s2s-microservice
          alias: IA_S2S_MICROSERVICE
        - name: prof-ref-data-url
          alias: PROF_REF_DATA_URL
        - name: launch-darkly-sdk-key
          alias: LAUNCH_DARKLY_SDK_KEY
        - name: case-api-POSTGRES-PASS-15
          alias: spring.datasource.password
        - name: app-insights-connection-string
          alias: app-insights-connection-string
        - name: postgres-auth-values-password
          alias: PG_AUTH_VALUES_YAML_PASS
        - name: docmosis-access-key
          alias: DOCMOSIS_ACCESS_KEY

ia-case-payments-api:
  enabled: false
ia-case-documents-api:
  enabled: false
ia-case-notifications-api:
  enabled: false
ia-home-office-integration-api:
  enabled: false
ia-bail-case-api:
  enabled: false
idam-pr:
  enabled: false
xui-webapp:
  enabled: false
ccd:
  enabled: false
ia-aip-frontend:
  enabled: false
ccd-case-document-am-api:
  enabled: false
em-ccdorc:
  enabled: false
em-stitching:
  enabled: false
wa:
  enabled: false
servicebus:
  enabled: false
ccd-message-publisher:
  enabled: false
aac-manage-case-assignment:
  enabled: false
am-org-role-mapping-service:
  enabled: false
redis:
  enabled: false