java:
  image: 'https://hmctspublic.azurecr.io/ia/case-api:latest'
  applicationPort: 8090
  aadIdentityName: ia
  environment:
    POSTGRES_PORT: 5432
    POSTGRES_HOST: ia-case-api-postgres-db-{{ .Values.global.environment }}.postgres.database.azure.com
    POSTGRES_USERNAME: ia_case_api@ia-case-api-postgres-db-{{ .Values.global.environment }}
    POSTGRES_CONNECTION_OPTIONS: "?sslmode=require"
    PROF_REF_DATA_URL: "http://rd-professional-api-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal"
  postgresql:
    postgresqlUsername: ia_case_api
    postgresqlPassword: ia_case_api
    postgresqlDatabase: ia_case_api
    service:
      port: 5432
  keyVaults:
    ia:
      secrets:
        - case-documents-api-url
        - case-notifications-api-url
        - docmosis-enabled
        - em-stitching-enabled
        - submit-hearing-requirements-enabled
        - system-username
        - system-password
        - idam-client-id
        - idam-secret
        - idam-redirect-uri
        - s2s-secret
        - s2s-microservice
        - ccd-url
        - ccd-gw-url
        - dm-url
        - idam-url
        - s2s-url
        - docmosis-enabled
        - em-stitching-enabled
        - case-api-POSTGRES-PASS
        - AppInsightsInstrumentationKey