java:
  image: 'https://hmctspublic.azurecr.io/ia/case-api:latest'
  ingressHost: ia-case-api-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
  applicationPort: 8090
  aadIdentityName: ia
  environment:
    POSTGRES_PORT: 5432
    POSTGRES_HOST: ia-case-api-postgres-11-db-{{ .Values.global.environment }}.postgres.database.azure.com
    POSTGRES_USERNAME: ia_case_api@ia-case-api-postgres-11-db-{{ .Values.global.environment }}
    POSTGRES_CONNECTION_OPTIONS: "?sslmode=require"
    PROF_REF_DATA_URL: "http://rd-professional-api-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal"
    REF_DATA_CASE_WORKER_URL: "http://rd-caseworker-ref-api-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal"
    IA_CASE_DOCUMENTS_API_URL: "http://ia-case-documents-api-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal/"
    IA_CASE_NOTIFICATIONS_API_URL: "http://ia-case-notifications-api-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal/"
    IA_TIMED_EVENT_SERVICE_URL: "http://ia-timed-event-service-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal/"
    IA_TIMED_EVENT_SERVICE_ENABLED: "false"
    IA_CASE_PAYMENTS_API_URL: "http://ia-case-payments-api-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal/"
    IA_HOME_OFFICE_INTEGRATION_API_URL: "http://ia-home-office-integration-api-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal/"
    IA_HOME_OFFICE_INTEGRATION_ENABLED: "false"
    IA_IDAM_REDIRECT_URI: "https://ia-case-api-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal/oauth2/callback"
    CCD_URL: "http://ccd-data-store-api-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal"
    AAC_URL: "http://aac-manage-case-assignment-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal"
    CCD_GW_URL: "http://dm-store-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal"
    DM_URL: "http://dm-store-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal"
    IDAM_URL: "https://idam-api.{{ .Values.global.environment }}.platform.hmcts.net"
    OPEN_ID_IDAM_URL: "https://idam-web-public.{{ .Values.global.environment }}.platform.hmcts.net"
    S2S_URL: "http://rpe-service-auth-provider-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal"
    IS_SAVE_AND_CONTINUE_ENABLED: "false"
    ROLE_ASSIGNMENT_URL: "http://am-role-assignment-service-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal"
    COMMON_DATA_API: http://rd-commondata-api-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
    CASE_DOCUMENT_AM_URL: "http://ccd-case-document-am-api-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal"
  postgresql:    
    auth:
      username: ia_case_api
      password: ia_case_api
      database: ia_case_api
    service:
      port: 5432
  keyVaults:
    ia:
      secrets:
        - docmosis-enabled
        - em-stitching-enabled
        - submit-hearing-requirements-enabled
        - system-username
        - system-password
        - idam-client-id
        - idam-secret
        - s2s-secret
        - s2s-microservice
        - prof-ref-data-url
        - docmosis-enabled
        - em-stitching-enabled
        - launch-darkly-sdk-key
        - case-api-POSTGRES-PASS-11
        - app-insights-connection-string
        
ia-case-payments-api:
  enabled: false
ia-case-documents-api:
  enabled: false
ia-case-notifications-api:
  enabled: false
ia-home-office-integration-api:
  enabled: false
idam-pr:
  enabled: false
xui-webapp:
  enabled: false
ccd:
  enabled: false
ia-aip-frontend:
  enabled: false
ccd-case-document-am-api:
  enabled: false
em-ccdorc:
  enabled: false
em-stitching:
  enabled: false
