apiVersion: v2
description: A Helm chart for Bail Case API App
name: ia-bail-case-api
home: https://github.com/hmcts/ia-bail-case-api
version: 0.0.15
maintainers:
  - name: Immigration & Asylum Team
    email: ImmigrationandAsylum@HMCTS.NET
dependencies:
  - name: java
    version: 4.0.13
    repository: https://hmctspublic.azurecr.io/helm/v1/repo/

