java:
  image: 'hmctspublic.azurecr.io/ia/bail-case-api:latest'
  applicationPort: 8686
  readinessPath: '/health/readiness'
  aadIdentityName: ia
  ingressHost: ia-bail-case-api-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
  environment:
    CCD_URL: "http://ccd-data-store-api-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal"
    AAC_URL: "http://aac-manage-case-assignment-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal"
    CCD_GW_URL: "http://dm-store-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal"
    DM_URL: "http://dm-store-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal"
    IA_IDAM_REDIRECT_URI: "https://ia-bail-case-api-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal/oauth2/callback"
    IDAM_URL: "https://idam-api.{{ .Values.global.environment }}.platform.hmcts.net"
    OPEN_ID_IDAM_URL: "https://idam-web-public.{{ .Values.global.environment }}.platform.hmcts.net"
    S2S_URL: "http://rpe-service-auth-provider-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal"
    PROF_REF_DATA_URL: "http://rd-professional-api-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal"
    IA_CASE_DOCUMENTS_API_URL: "http://ia-case-documents-api-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal/"
    IA_CASE_NOTIFICATIONS_API_URL: "http://ia-case-notifications-api-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal/"
    CASE_DOCUMENT_AM_URL: "http://ccd-case-document-am-api-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal"
    COMMON_DATA_API: http://rd-commondata-api-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
  keyVaults:
    ia:
      resourceGroup: ia
      secrets:
        - name: docmosis-enabled
          alias: IA_DOCMOSIS_ENABLED
        - name: em-stitching-enabled
          alias: IA_EM_STITCHING_ENABLED
        - name: system-username
          alias: IA_SYSTEM_USERNAME
        - name: system-password
          alias: IA_SYSTEM_PASSWORD
        - name: idam-client-id
          alias: IA_IDAM_CLIENT_ID
        - name: idam-secret
          alias: IA_IDAM_SECRET
        - name: s2s-secret
          alias: IA_S2S_SECRET
        - name: s2s-microservice
          alias: IA_S2S_MICROSERVICE
        - name: prof-ref-data-url
          alias: PROF_REF_DATA_URL
        - name: launch-darkly-sdk-key
          alias: LAUNCH_DARKLY_SDK_KEY
        - name: app-insights-connection-string
          alias: app-insights-connection-string
        - name: ia-config-validator-secret
          alias: IA_CONFIG_VALIDATOR_SECRET
